services:
  rtsp:
    build: .
    environment:
      TZ: Europe/Berlin
      # rtsp config
      RTSP_USER: abc
      RTSP_PASS: abc
      RTSP_HOST: 192.168.1.1
      # RTSP_PORT: 554
      # RTSP_PATH: stream1
      #
      # how often to take a screenshot
      INTERVAL_SCREENSHOT_MINUTES: 10
      # when to generate timelapse
      TIMELAPSE_GENERATION_TIME: 14:00
      #
      LOGGING_LEVEL: ERROR  # suppress unnecessary messages
      TIMELAPSE_CRF: 28  # CRF of timelapse videos
      #
      # notification settings, where to send videos once generated
      # separate by comma or space
      # https://github.com/caronc/apprise/wiki/config
      # APPRISE_SERVERS: discord://1234/abc1234
    volumes:
      - data:/app/data

volumes:
  data:
