services:
  rtsp:
    build: .
    environment:
      TZ: Europe/Berlin
      # rtsp config
      RTSP_URL: rtsp://abc:abc@192.168.1.1:554/stream1
      #
      # how often to take a screenshot
      INTERVAL_SCREENSHOT_MINUTES: 10
      # when to generate timelapse
      TIMELAPSE_GENERATION_TIME: 14:00
      # skip time range, e.g. when it's night
      SKIP_TIME_START: 14:30
      SKIP_TIME_END: 19:30
      #
      LOGGING_LEVEL: ERROR  # suppress unnecessary messages
      TIMELAPSE_CRF: 28  # CRF of timelapse videos
      #
      # notification settings, where to send videos once generated
      # separate by comma or space
      # https://github.com/caronc/apprise/wiki/config
      # APPRISE_SERVERS: discord://1234/abc1234
    volumes:
      - data:/app/data

volumes:
  data:
